<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><IsPackable>false</IsPackable><LangVersion>14.0</LangVersion><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><RootNamespace>Commandes.Tests</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../S09E01_Commandes.Application/S09E01_Commandes.Application.csproj" /><ProjectReference Include="../S09E01_Commandes.Domaine/S09E01_Commandes.Domaine.csproj" /><ProjectReference Include="../S09E01_Commandes.Infrastructure/S09E01_Commandes.Infrastructure.csproj" /><PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" /><PackageReference Include="xunit" Version="2.9.3" /><PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" /></ItemGroup></Project>
