<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><LangVersion>14.0</LangVersion><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><RootNamespace>Commandes.Infrastructure</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../S10E01_Facturation.Application/S10E01_Facturation.Application.csproj" /><ProjectReference Include="../S10E01_Facturation.Domaine/S10E01_Facturation.Domaine.csproj" /></ItemGroup></Project>
