<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><LangVersion>14.0</LangVersion><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><RootNamespace>Commandes.Terminal</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../S10E01_Facturation.Presentation/S10E01_Facturation.Presentation.csproj" /><ProjectReference Include="../S10E01_Facturation.Application/S10E01_Facturation.Application.csproj" /><ProjectReference Include="../S10E01_Facturation.Infrastructure/S10E01_Facturation.Infrastructure.csproj" /></ItemGroup></Project>
